name:                haskoin
version:             0.1.0.0
github:              "lambdaeon/haskoin"
license:             BSD3
author:              "λeon"
maintainer:          "lambdaeon@protonmail.com"
copyright:           "2022 ΛEON"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Bitcoin implementation in Haskell.

dependencies:
- base >= 4.7 && < 5
- base16
- binary
- bytestring
- conduit
- conduit-extra
- containers
- cryptonite
- groups
- http-client
- http-client-tls
- http-conduit
- megaparsec
- memory
- mtl
- network
- text
- time
- transformers

default-extensions:
- OverloadedStrings
- RecordWildCards
- DataKinds
- KindSignatures
- ScopedTypeVariables
- TupleSections
- NumericUnderscores
- FlexibleInstances

library:
  source-dirs: src

executables:
  haskoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base16
    - binary
    - bytestring
    - conduit
    - conduit-extra
    - containers
    - cryptonite
    - groups
    - http-client
    - http-client-tls
    - http-conduit
    - haskoin
    - hspec
    - megaparsec
    - memory
    - mtl
    - network
    - text
    - time
    - transformers

tests:
  haskoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cryptonite
    - haskoin
    - hspec
    - hspec-megaparsec
    - megaparsec
    - memory
    - mtl
    - text
    - transformers
